component:
  id: "athena_knowledge"
  name: "Athena Knowledge Graph"
  version: "0.1.0"
  description: "Knowledge graph service for semantic entity management and queries"
  port: 8005

capabilities:
  - id: "knowledge_graph"
    name: "Knowledge Graph"
    description: "Manage entities and relationships in a knowledge graph"
    methods:
      - id: "add_entity"
        name: "Add Entity"
        description: "Add a new entity to the knowledge graph"
        parameters:
          - name: "entity_type"
            type: "string"
            required: true
          - name: "properties"
            type: "object"
            required: true
        returns:
          type: "object"
          
      - id: "add_relationship"
        name: "Add Relationship"
        description: "Add a relationship between entities"
        parameters:
          - name: "source_id"
            type: "string"
            required: true
          - name: "target_id"
            type: "string"
            required: true
          - name: "relationship_type"
            type: "string"
            required: true
          - name: "properties"
            type: "object"
            required: false
        returns:
          type: "object"
          
      - id: "query"
        name: "Query Knowledge Graph"
        description: "Query entities and relationships"
        parameters:
          - name: "query"
            type: "string"
            required: true
        returns:
          type: "array"