component:
  id: "engram"
  name: "Engram Memory System"
  version: "0.1.0"
  description: "Advanced memory and vector database system"
  port: 8000
  host: "localhost"
  url: "http://localhost:8000"
  health_endpoint: "/health"
  metadata:
    description: "Memory and knowledge storage system"
    version: "0.1.0"
    dependencies: ["hermes"]

capabilities:
  - id: "memory_management"
    name: "Memory Management"
    description: "Create and manage memory collections"
    methods:
      - id: "store_memory"
        name: "Store Memory"
        description: "Store a new memory in the system"
        parameters:
          - name: "content"
            type: "string"
            required: true
          - name: "metadata"
            type: "object"
            required: false
          - name: "collection"
            type: "string"
            required: false
        returns:
          type: "object"
          
      - id: "retrieve_memory"
        name: "Retrieve Memory"
        description: "Retrieve memories by similarity search"
        parameters:
          - name: "query"
            type: "string"
            required: true
          - name: "collection"
            type: "string"
            required: false
          - name: "limit"
            type: "integer"
            required: false
        returns:
          type: "object"
          
      - id: "create_collection"
        name: "Create Collection"
        description: "Create a new memory collection"
        parameters:
          - name: "name"
            type: "string"
            required: true
          - name: "description"
            type: "string"
            required: false
          - name: "embedding_model"
            type: "string"
            required: false
        returns:
          type: "object"
          
  - id: "structured_memory"
    name: "Structured Memory"
    description: "Work with structured memory objects"
    methods:
      - id: "store_structured_memory"
        name: "Store Structured Memory"
        description: "Store a structured memory with relationships"
        parameters:
          - name: "content"
            type: "object"
            required: true
          - name: "relationships"
            type: "array"
            required: false
          - name: "metadata"
            type: "object"
            required: false
        returns:
          type: "object"
          
      - id: "retrieve_structured_memory"
        name: "Retrieve Structured Memory"
        description: "Retrieve structured memories with relationship data"
        parameters:
          - name: "query"
            type: "string"
            required: true
          - name: "include_relationships"
            type: "boolean"
            required: false
          - name: "limit"
            type: "integer"
            required: false
        returns:
          type: "object"