component:
  id: "ergon-memory"
  name: "Ergon Memory Service"
  version: "0.1.0"
  description: "Document and memory management for agents"
  port: 8002
  metadata:
    component_type: "service"

capabilities:
  - id: "document_storage"
    name: "Document Storage"
    description: "Store and retrieve documents"
    methods:
      - id: "store_document"
        name: "Store Document"
        description: "Store a document in the memory system"
        parameters:
          - name: "document"
            type: "object"
            required: true
          - name: "metadata"
            type: "object"
            required: false
        returns:
          type: "object"
          
      - id: "get_document"
        name: "Get Document"
        description: "Retrieve a document by ID"
        parameters:
          - name: "document_id"
            type: "string"
            required: true
        returns:
          type: "object"
          
  - id: "vector_search"
    name: "Vector Search"
    description: "Semantic search across documents"
    methods:
      - id: "search"
        name: "Semantic Search"
        description: "Search for documents using semantic similarity"
        parameters:
          - name: "query"
            type: "string"
            required: true
          - name: "limit"
            type: "number"
            required: false
          - name: "filters"
            type: "object"
            required: false
        returns:
          type: "array"
          
  - id: "memory_management"
    name: "Memory Management"
    description: "Manage agent memory systems"
    methods:
      - id: "create_memory"
        name: "Create Memory"
        description: "Create a new memory space for an agent"
        parameters:
          - name: "agent_id"
            type: "string"
            required: true
          - name: "memory_type"
            type: "string"
            required: true
          - name: "config"
            type: "object"
            required: false
        returns:
          type: "object"
          
      - id: "update_memory"
        name: "Update Memory"
        description: "Update an agent's memory with new information"
        parameters:
          - name: "memory_id"
            type: "string"
            required: true
          - name: "content"
            type: "object"
            required: true
        returns:
          type: "object"