component:
  id: prometheus
  name: Prometheus Planning System
  description: Intelligent planning and retrospective analysis system for project management
  type: service
  version: 0.1.0
  port: 8006
  host: localhost
  url: http://localhost:8006
  health_endpoint: /health
component_capabilities:
  - planning
  - risk_analysis
  - retrospective_analysis
  - improvement_suggestions
  - critical_path_analysis
component_dependencies:
  - rhetor
  - engram
  - telos
component_tags:
  - planning
  - project_management
  - llm_integration
  - risk_analysis
  - retrospective
component_registration:
  hermes_url: "http://localhost:8001/api/registration"
  auto_register: true
component_routes:
  - path: "/api"
    type: "http"
    description: "HTTP API endpoints"
  - path: "/api/v1/llm"
    type: "http"
    description: "LLM integration endpoints"