component:
  id: "sophia.embedding"
  name: "Sophia Embedding Service"
  version: "0.1.0"
  description: "Text embedding service"
  port: 5500
  metadata:
    component: "sophia"
    description: "Text embedding service"
    dimensions: 384
    model: "sophia-embedding-small"

capabilities:
  - id: "embeddings"
    name: "Embeddings"
    description: "Generate vector embeddings for text"
    methods:
      - id: "embed_text"
        name: "Embed Text"
        description: "Generate vector embeddings for text"
        parameters:
          - name: "text"
            type: "string"
            required: true
          - name: "model"
            type: "string"
            required: false
        returns:
          type: "object"
          
      - id: "batch_embed"
        name: "Batch Embed"
        description: "Generate embeddings for multiple texts"
        parameters:
          - name: "texts"
            type: "array"
            required: true
          - name: "model"
            type: "string"
            required: false
        returns:
          type: "array"
          
  - id: "vector_operations"
    name: "Vector Operations"
    description: "Perform operations on vector embeddings"
    methods:
      - id: "calculate_similarity"
        name: "Calculate Similarity"
        description: "Calculate similarity between vectors"
        parameters:
          - name: "vector1"
            type: "array"
            required: true
          - name: "vector2"
            type: "array"
            required: true
          - name: "metric"
            type: "string"
            required: false
        returns:
          type: "number"