component:
  id: "sophia.ml"
  name: "Sophia ML Engine"
  version: "0.1.0"
  description: "Machine learning and embedding component for Tekton"
  port: 5500
  metadata:
    description: "Machine learning and embedding component for Tekton"
    models:
      embedding:
        default: "sophia-embedding-small"
        dimensions: 384
      classification:
        default: "sophia-classification-base"

capabilities:
  - id: "embeddings"
    name: "Embeddings"
    description: "Generate vector embeddings for text"
    methods:
      - id: "generate_embeddings"
        name: "Generate Embeddings"
        description: "Generate vector embeddings for text"
        parameters:
          - name: "text"
            type: "string"
            required: true
          - name: "model_id"
            type: "string"
            required: false
        returns:
          type: "object"
          
  - id: "classification"
    name: "Classification"
    description: "Classify text into categories"
    methods:
      - id: "classify_text"
        name: "Classify Text"
        description: "Classify text into categories"
        parameters:
          - name: "text"
            type: "string"
            required: true
          - name: "categories"
            type: "array"
            required: true
          - name: "model_id"
            type: "string"
            required: false
        returns:
          type: "object"
          
  - id: "model_management"
    name: "Model Management"
    description: "Manage machine learning models"
    methods:
      - id: "register_model"
        name: "Register Model"
        description: "Register a new machine learning model"
        parameters:
          - name: "model_id"
            type: "string"
            required: true
          - name: "model_type"
            type: "string"
            required: true
          - name: "provider"
            type: "string"
            required: true
          - name: "capabilities"
            type: "array"
            required: true
          - name: "metadata"
            type: "object"
            required: false
        returns:
          type: "object"
          
      - id: "get_model_status"
        name: "Get Model Status"
        description: "Get the status of all registered models"
        parameters: []
        returns:
          type: "object"