component:
  id: "terma.terminal"
  name: "Terma"
  version: "0.1.0"
  description: "Terminal integration system for Tekton"
  port: 8765
  metadata:
    endpoints:
      api: "http://localhost:8765/api"
      websocket: "ws://localhost:8765/ws"

capabilities:
  - id: "terminal_management"
    name: "Terminal Management"
    description: "Manage terminal sessions"
    methods:
      - id: "terminal.create"
        name: "Create Terminal"
        description: "Create a new terminal session"
        parameters:
          - name: "shell_command"
            type: "string"
            required: false
        returns:
          type: "object"
          
      - id: "terminal.close"
        name: "Close Terminal"
        description: "Close a terminal session"
        parameters:
          - name: "session_id"
            type: "string"
            required: true
        returns:
          type: "object"
          
  - id: "terminal_io"
    name: "Terminal I/O"
    description: "Terminal input/output operations"
    methods:
      - id: "terminal.write"
        name: "Write to Terminal"
        description: "Write data to a terminal session"
        parameters:
          - name: "session_id"
            type: "string"
            required: true
          - name: "data"
            type: "string"
            required: true
        returns:
          type: "object"
          
      - id: "terminal.read"
        name: "Read from Terminal"
        description: "Read data from a terminal session"
        parameters:
          - name: "session_id"
            type: "string"
            required: true
        returns:
          type: "object"